version: '3.4'

services:
  ssoserver:
    image: ${DOCKER_REGISTRY-}ssoserver
    build:
      context: .
      dockerfile: src/SsoServer/Dockerfile
    ports:
      - "1080:80"
      - "1443:443"
    networks:
      nginx-letsencrypt_mynetwork:
        ipv4_address: 172.21.0.6
networks:
  nginx-letsencrypt_mynetwork:
    external: true
